### ISSUE TITLE
SciChartBlazor has PaletteProviding feature same as WPF?

### ISSUE THREAD

**Issue by dhruvindudhat** [NRTDP/SciChartBlazor#11]
Can you please tell me is there a functionality called "PaletteProvider"(changes color of series on certain point range[Line chart]) in ScichartBlazor same as WPF?

**Comment by mikehollas123** [comment]
In Blazor, no. That's a more complicated implementation, and SciChartBlazor is just a wrapper around SciChart JS. In SciChartJS, yes! [https://www.scichart.com/documentation/js/current/The%20PaletteProvider%20API.html#:~:text=The%20PaletteProvider%20API%20is%20a,based%20on%20a%20programatic%20rule.](https://www.scichart.com/documentation/js/current/The%20PaletteProvider%20API.html#:~:text=The%20PaletteProvider%20API%20is%20a,based%20on%20a%20programatic%20rule.)

You have to create your own class, and then add it to a series. I don't think that would be easy with a wrapper.

Hope this helps.

**Comment by dhruvindudhat** [comment]
@mikehollas123  Can you add this feature to the wrapper? This feature is a must-have for my case, If you add it this will be more helpful for me.

**Comment by mikehollas123** [comment]
This is something that is highly custom. I can’t do it for you. [here are some instructions ](https://www.scichart.com/documentation/js/current/Per-point%20Colouring%20of%20Line%20Segments.html) on how to do this in JS. After you’ve created the class in JS, you can register it with the builder. Then if you make a c# wrapper for your custom palateprovider you can use it in the c# wrapper
