### ISSUE TITLE
Want to show x-axis coordinates as string instead of double in column chart

### ISSUE THREAD

**Issue by dhruvindudhat** [NRTDP/SciChartBlazor#16]
I want to show x-axis coordinates as string (ex. Apple, Banana, Mango) instead of double in column chart and take y-axis as double value.
How can we achieve that? can you guide?

**Comment by mikehollas123** [comment]
Hi I don't really have time to look into this. but you can find the JS documentation here: https://www.scichart.com/documentation/js/current/TextStringAxis.html

you should be able to make a TextLabelProvider class with: 
`public override string Type => "Text";

public string[] Labels {get ;set;} 
`

This might need some work to get it functional.

**Comment by mikehollas123** [comment]
Also add this to AxisBase.cs:

    [HasOptions]
    public TextLabelProvider? LabelProvider { get; set; }

you might want to set up an interface for the LabelProvider
