### ISSUE TITLE
License Version of Scichart Js is not showing charts in other machines (Release Mode)

### ISSUE THREAD

**Issue by dhruvindudhat** [NRTDP/SciChartBlazor#19]
I am creating **.Net MAUI Blazor Hybrid Application** (Window Application) and during development, I am using a trial version of sci chart js and setting up that version runtime key. It works fine on my machine and also on other machines.

Finally, I have purchased a scichart js license and set up the runtime key in the code.

In debug mode charts are visible in my machine but not in others due to one developer access which is correct!
But the strange thing is in release mode charts are not visible too... This cause an huge problem!! which is working in trial version. I have tested this in other machines also same thing happens.

Please review below error screenshot.
![MicrosoftTeams-image](https://github.com/NRTDP/SciChartBlazor/assets/77716875/71c160a7-cc1c-4f17-a2d6-dc3a1dc1c1d8)

@mikehollas123 @andyb1979 @rfellers Is there anything wrong here? Can you please help me ASAP? This is on urgent basis.

**Comment by andyb1979** [comment]
This might be a problem to share with us on scichart support with a minimal visual studio solution that reproduces the issue. Licensing, for all the myriad javascript frameworks is a bit of a headache, but typically we can find solutions for all!
