### ISSUE TITLE
Add possibility to use StrokeDashArray for line-based series.

### ISSUE THREAD

**Issue by Digitaalne** [NRTDP/SciChartBlazor#20]
Hello, mainly in need of **StokeDashArray** property for _FastLineRenderableSeries_, but read from here https://www.scichart.com/documentation/js/current/webframe.html#Series%20Styling%20-%20Dash%20Line%20Patterns.html that "All the line-based series in SciChart.js support _**StrokeDashArray**_ for dashed or dotted lines." So thought it will be useful for all, not only FastLineRenderableSeries.

**Comment by mikehollas123** [comment]
I don't have a lot of time to maintain this. However, if you want to take a stab at this, you likely can create a new Interface ILineSeries or something like that. Please feel free to do a PR (with a demo of it working) and I'll be happy to add it

**Comment by mikehollas123** [comment]
Looks like you did! Please add something to the demos showing it working and I'll be happy to merge
