### ISSUE TITLE
Getting Error "This version of SciChart is too old to be trialed"

### ISSUE THREAD

**Issue by dhruvindudhat** [NRTDP/SciChartBlazor#6]
ScichartBlazor nuGet Package v1.0.0.0
Scichart v2.2.2415

Getting Below Error:
Sorry! This version of SciChart is too old to be trialed. Please update to the latest version
Looking for Licensing Wizard... Please run it or click for download and installation instructions.

Is there anything suspicious?

**Comment by andyb1979** [comment]
That's because SciChart.js itself encourages you to update to latest version. This is related to issue #5 - Test and update to SciChart.js v3

**Comment by dhruvindudhat** [comment]
Can you guide How to Upgrade SciChart.js to v3 from older version?

**Comment by mikehollas123** [comment]
We've just released an update that uses SchiChart.js v3 #7
