### ISSUE TITLE
MouseWheelZoomModifier feature is not working properly

### ISSUE THREAD

**Issue by dhruvindudhat** [NRTDP/SciChartBlazor#8]
When I try to zoom in/out using mouse, Chart not zoom in/out Y-axis even I set
 XyDirection = XyDirection.XyDirection
and X-Axis is working properly.

Can you guide is there anything wrong or miss to set anything?

**Comment by mikehollas123** [comment]
Hi @dhruvindudhat,
Thanks for reaching out, and welcome!

I threw together some quick code to test this out and it looks like it works as expected. XyDirection.XyDirection is the default behavior. I suspect the issue you're having is that in the Y axis `AutoRange = AutoRange.Always`   (this is the case in the example wasm LineRenderableSeriesChartExample test). This will effectively override the XyDirection, and it will resize the Y axis every time it changes. Try changing this to Once or Never. 

Hope this helps!

**Comment by dhruvindudhat** [comment]
@mikehollas123 Thanks for helping, Looks like it is working fine! You may close this issue.
